In [10]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# python

## python explainer

In [11]:
1+2

3

### calculation

In [12]:
1-2
4*5
7/5
3**2

-1

20

1.4

9

### data type

In [13]:
type(2)
type(2.718)
type("hello")

int

float

str

### variable

In [14]:
x = 10
print(x)
x = 100
print(x)
y = 3.14
x * y
type(x * y)

10
100


314.0

float

### list

In [16]:
a = [1,2,3,4,5]
print(a)
len(a)
a[0]
a[4]
a[4] = 99
print(a)

[1, 2, 3, 4, 5]


5

1

5

[1, 2, 3, 4, 99]


In [22]:
print(a)
a[0:2] # not include 2
a[1:]
a[:3]
a[:-1]
a[:-2]

[1, 2, 3, 4, 99]


[1, 2]

[2, 3, 4, 99]

[1, 2, 3]

[1, 2, 3, 4]

[1, 2, 3]

### dictionary

In [23]:
me = {"height":180}
me["height"]
me["weight"] = 70
print(me)

180

{'height': 180, 'weight': 70}


### boolean

In [24]:
hungry = True
sleepy = False
type(hungry)
not hungry
hungry and sleepy
hungry or sleepy

bool

False

False

True

### if structure

In [25]:
hungry = True
if hungry:
    print("I'm hungry")

hungry = False
if hungry:
    print("I'm hungry")
else:
    print("I'm not hungry")
    print("I'm sleepy")

I'm hungry
I'm not hungry
I'm sleepy


### for structure

In [26]:
for i in [1, 2, 3]:
    print(i)

1
2
3


### function

In [27]:
def hello():
    print("Hello World!")

hello()

Hello World!


In [28]:
def hello(object):
    print("Hello " + object + "!")

hello("cat")

Hello cat!


## py script

### class

In [ ]:
class Man:
    def __init__(self, name):  # constructor
        self.name = name
        print("Initialized!")

    def hello(self):
        print("Hello" + self.name + "!")
    
    def goodbye(self):
        print("Good-bye" + self.name + "!")

m = Man("David")
m.hello()
m.goodbye()

Initialized!
HelloDavid!
Good-byeDavid!


## NumPy

In [ ]:
import numpy as np

# generate

x = np.array([1.0,2.0,3.0])
print(x)
type(x)

# calculate
x = np.array([1.0,2.0,3.0])  # element-wise
y = np.array([2.0,4.0,6.0])
x + y
x - y
x * y 
x / y 

[1. 2. 3.]


numpy.ndarray

array([3., 6., 9.])

array([-1., -2., -3.])

array([ 2.,  8., 18.])

array([0.5, 0.5, 0.5])